#/bin/sh
php artisan restaurant:delete dadda                   
php artisan restaurant:delete lanka                   
php artisan restaurant:delete testtest                    
php artisan restaurant:delete testtestdddd                    
php artisan restaurant:delete boardingbusinessowner                   
php artisan restaurant:delete titit                   
php artisan restaurant:delete testmode                    
php artisan restaurant:delete fsdfasd                 
php artisan restaurant:delete seafasdf                    
php artisan restaurant:delete asdffsd                 
php artisan restaurant:delete fasdasfd                    
php artisan restaurant:delete hflalskj                    
php artisan restaurant:delete fgsadgsdfag                 
php artisan restaurant:delete popane5946                  
php artisan restaurant:delete testmodemenuat                  
php artisan restaurant:delete cilmuyukke                  
php artisan restaurant:delete fdasfasdfsadf                   
php artisan restaurant:delete gfdsfgdsf                   
php artisan restaurant:delete bendover                    
php artisan restaurant:delete nathanielfunk                   
php artisan restaurant:delete testdemo                    
php artisan restaurant:delete testfsaf                    
php artisan restaurant:delete asdfasdf                    
php artisan restaurant:delete asfd                    
php artisan restaurant:delete asffsdgfsd     
